# Generated by Django 3.1 on 2020-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_auto_20201111_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
