# Generated by Django 3.1 on 2020-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='warehouse',
            field=models.CharField(default="Not Given", max_length=100),
            preserve_default=False,
        ),
    ]
