# Generated by Django 3.1 on 2020-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0009_addrecord_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='warehouse',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
